spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console