on:
    pull_request:
        types:
            - 'closed'
        branches:
            - 'main'
jobs:
    build:
        
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'graalvm'
            - run: echo "Compile native into ${{ matrix.os }}"