on:
    push:
        branches:
            - 'releases/**'
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [11, 17, 21]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                java-version: ${{ matrix.node }}
                distribution: 'temurin'
            - run: echo "Building with ${{ matrix.node }}"

            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-dummy-jdk${{ matrix.node }}
                path: README.md