on:
    release:
        types: [published]

jobs:
    build:
        
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write

        steps:
            #- name: Dump GitHub context
            #  env:
            #    GITHUB_CONTEXT: ${{ toJson(github) }}
            #  run: echo "$GITHUB_CONTEXT"
            #- run: echo "$GITHUB_REF_NAME"

            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'graalvm'
            - run: echo "Compile native into ${{ matrix.os }}"

            - name: Build project # This would actually build your project, using zip for an example artifact
              run: |
                  7z a dist-client-pde-sb-${{ matrix.os }}.zip README.md

            - name: Upload Release Asset
              id: upload-release-asset
              #run: gh release upload ${{github.event.release.tag_name}} $ASSET_PATH
              # Fail for Windows: requires al least 2 arg(s)
              #run: gh api --method POST --hostname github.com /repos/$OWNER/$REPO/releases/$RELEASE_ID/assets?name=$ASSET_NAME -f '@'$ASSET_PATH
              # Fail: invalid key: "@./dist-client-pde-sb-ubuntu-latest.zip"
              run: |
                curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/$OWNER/$REPO/releases/$RELEASE_ID/assets?name=$ASSET_NAME" --data-binary "@$ASSET_PATH"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OWNER: ${{ github.repository_owner }}
                  REPO: ${{ github.event.repository.name }}
                  RELEASE_ID: ${{ github.event.release.id }}
                  ASSET_NAME: dist-client-pde-sb-${{ matrix.os }}.zip
                  ASSET_PATH: ./dist-client-pde-sb-${{ matrix.os }}.zip